'use client'

import Link from 'next/link'
import Image from 'next/image'
import { Check, ChevronLeft, LoaderCircle, Ruler, RotateCcw, Send, ShoppingBag, Sparkles } from 'lucide-react'
import { useCart } from '@payloadcms/plugin-ecommerce/client/react'
import { useEffect, useMemo, useState } from 'react'
import { toast } from 'sonner'

import type { AdvisorProductVariant, AdvisorRecommendation } from '@/lib/ai-home-advisor/catalog/catalogue-types'
import { availableColourFamilies, availableLengths, availableLightPreferences, availablePatterns, emptyCurtainFinderState, filterCurtainCandidates, labelForLength, resetDependentAnswers, type ColourFamily, type CurtainFinderState, type InstallationType, type LightPreference, type PatternPreference } from '@/lib/ai-home-advisor/guided/curtain-flow'
import './guided-advisor.css'

type StepID = 'installation' | 'length' | 'light' | 'colour' | 'pattern'
type Option = { value: string; label: string; description: string; count: number; tone?: string }
const formatPrice = (value: number | null) => value === null ? 'Price unavailable' : new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value / 100)
const title = (value: string) => value.replaceAll('-', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())

function AddRecommendation({ product }: { product: AdvisorRecommendation }) {
  const { addItem, isLoading } = useCart()
  return <button className="guided-add" disabled={isLoading} onClick={() => void addItem({ product: Number(product.familyId), variant: product.variantId || undefined }).then(() => toast.success('Added to your bag.')).catch(() => toast.error('Please try adding this from the product page.'))} type="button"><ShoppingBag size={15} /> Add to bag</button>
}

export function GuidedAdvisor() {
  const [products, setProducts] = useState<AdvisorProductVariant[]>([])
  const [state, setState] = useState<CurtainFinderState>(emptyCurtainFinderState)
  const [mode, setMode] = useState<'hero' | 'wizard' | 'results'>('hero')
  const [stepIndex, setStepIndex] = useState(0)
  const [measureOpen, setMeasureOpen] = useState(false)
  const [measurement, setMeasurement] = useState('')
  const [unit, setUnit] = useState<'feet' | 'inches' | 'cm'>('feet')
  const [customOpen, setCustomOpen] = useState(false)
  const [customText, setCustomText] = useState('')
  const [interpreted, setInterpreted] = useState(false)
  const [loading, setLoading] = useState(true)
  const [resultLoading, setResultLoading] = useState(false)
  const [results, setResults] = useState<AdvisorRecommendation[]>([])

  useEffect(() => { fetch('/api/ai-home-advisor/catalogue-options').then((response) => response.ok ? response.json() : null).then((data) => setProducts(data?.variants || [])).catch(() => toast.error('The curtain finder could not load.')).finally(() => setLoading(false)) }, [])
  const candidates = useMemo(() => filterCurtainCandidates(products, state), [products, state])
  const staged = (patch: Partial<CurtainFinderState>) => filterCurtainCandidates(products, { ...state, ...patch })
  const patternIsUseful = candidates.length > 4 && availablePatterns(candidates).length > 1
  const steps: StepID[] = ['installation', 'length', 'light', 'colour', ...(patternIsUseful ? ['pattern' as const] : [])]
  const activeStep = steps[Math.min(stepIndex, steps.length - 1)]

  const options = (): Option[] => {
    if (activeStep === 'installation') return [
      ['window', 'Window', 'For bedroom, living-room and kids-room windows'], ['door', 'Door', 'For standard room doors and shorter balcony openings'], ['balcony-long-door', 'Balcony or long door', 'For taller balcony doors and floor-length openings'],
    ].map(([value, label, description]) => ({ value, label, description, count: staged({ installationType: value as InstallationType }).length }))
    if (activeStep === 'length') return availableLengths(candidates).map((value) => ({ value: String(value), label: labelForLength(value), description: 'Measured from the top of the curtain rod', count: staged({ requiredLengthInches: value }).length }))
    if (activeStep === 'light') return availableLightPreferences(candidates).map((value) => ({ value, label: value === 'bright' ? 'Keep the room bright' : value === 'more-private' ? 'More privacy and less light' : 'Complete darkness', description: value === 'bright' ? 'Softens daylight while keeping the room naturally bright' : value === 'more-private' ? 'Verified room-darkening options' : 'Verified blackout options only', count: staged({ opacityPreference: value }).length }))
    if (activeStep === 'colour') return [...availableColourFamilies(candidates), 'all' as const].map((value) => ({ value, label: value === 'all' ? 'Show me everything' : title(value), description: value === 'all' ? 'Keep every available colour' : `${value === 'neutral' ? 'Calm, versatile tones' : 'Available colours in this mood'}`, count: staged({ colourFamily: value as ColourFamily }).length, tone: value }))
    return [...availablePatterns(candidates), 'all' as const].map((value) => ({ value, label: value === 'all' ? 'No preference' : title(value), description: value === 'all' ? 'Keep every pattern' : 'Available in the current matches', count: staged({ pattern: value as PatternPreference }).length }))
  }
  const question = activeStep === 'installation' ? ['Where will you install the curtain?', 'Choose the opening you want to cover.'] : activeStep === 'length' ? ['What curtain length do you need?', 'Measure from the top of the curtain rod to where you want the fabric to end.'] : activeStep === 'light' ? ['How much light do you want in the room?', 'Choose the result you want, not a technical curtain term.'] : activeStep === 'colour' ? ['Which colour mood suits your room?', 'Choose a broad look. You can change the exact colour later.'] : ['Which design do you prefer?', 'This is optional and only shows when it narrows the available curtains.']
  const summary = [state.installationType && ['Installation', state.installationType === 'balcony-long-door' ? 'Balcony / long door' : title(state.installationType)], state.requiredLengthInches && ['Length', labelForLength(state.requiredLengthInches)], state.opacityPreference && ['Light', state.opacityPreference === 'bright' ? 'Keep room bright' : state.opacityPreference === 'more-private' ? 'More privacy' : 'Blackout'], state.colourFamily && ['Colour', state.colourFamily === 'all' ? 'All colours' : title(state.colourFamily)], state.pattern && ['Pattern', state.pattern === 'all' ? 'No preference' : title(state.pattern)]].filter(Boolean) as [string, string][]

  const setAnswer = (value: string) => {
    let key: keyof CurtainFinderState = 'installationType'
    let patch: Partial<CurtainFinderState> = {}
    if (activeStep === 'installation') { key = 'installationType'; patch = { installationType: value as InstallationType } }
    if (activeStep === 'length') { key = 'requiredLengthInches'; patch = { requiredLengthInches: Number(value) } }
    if (activeStep === 'light') { key = 'opacityPreference'; patch = { opacityPreference: value as LightPreference } }
    if (activeStep === 'colour') { key = 'colourFamily'; patch = { colourFamily: value as ColourFamily } }
    if (activeStep === 'pattern') { key = 'pattern'; patch = { pattern: value as PatternPreference } }
    setState((current) => ({ ...resetDependentAnswers(current, key), ...patch }))
  }
  const next = () => { if (stepIndex < steps.length - 1) setStepIndex((current) => current + 1); else void showResults() }
  const back = () => { if (stepIndex > 0) setStepIndex((current) => current - 1); else setMode('hero') }
  const showResults = async (nextState: CurtainFinderState = state) => {
    const matchingProducts = filterCurtainCandidates(products, nextState)
    setResultLoading(true)
    const need = nextState.opacityPreference === 'bright' ? 'light filtering' : nextState.opacityPreference === 'more-private' ? 'room darkening' : nextState.opacityPreference === 'blackout' ? 'blackout' : null
    try { const response = await fetch('/api/ai-home-advisor/recommend', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ requirement: { language: 'english', intent: 'product-recommendation', categorySlug: 'curtains', productType: nextState.installationType === 'window' ? 'Window' : 'Door', room: null, application: nextState.installationType, needs: need ? [need] : [], preferredColours: nextState.colourFamily && nextState.colourFamily !== 'all' ? [nextState.colourFamily] : [], preferredPatterns: nextState.pattern && nextState.pattern !== 'all' ? [nextState.pattern] : [], preferredMaterials: [], preferredStyles: [], budgetMinPaise: nextState.budgetMinPaise, budgetMaxPaise: nextState.budgetMaxPaise, measurements: { widthCm: null, heightCm: nextState.requiredLengthInches ? Math.round(nextState.requiredLengthInches * 2.54) : null, lengthCm: null, mattressWidthCm: null, mattressLengthCm: null, mattressDepthCm: null }, missingRequiredFields: [], nextQuestion: null }, candidateIDs: matchingProducts.map((product) => product.id) }) }); const data = await response.json(); if (!response.ok) throw new Error(); setState(nextState); setResults(data.recommendations || []); setMode('results') } catch { toast.error('Could not prepare the matches. Please try again.') } finally { setResultLoading(false) }
  }
  const applyMeasurement = () => { const value = Number(measurement); if (!value) return; const inches = unit === 'feet' ? Math.round(value * 12) : unit === 'cm' ? Math.round(value / 2.54) : Math.round(value); if (!availableLengths(candidates).includes(inches)) { toast.message('That exact ready-made length is not available in this selection. Choose one of the available lengths instead.'); return } setAnswer(String(inches)); setMeasureOpen(false) }
  const customSubmit = async () => { if (!customText.trim()) return; setLoading(true); try { const response = await fetch('/api/ai-home-advisor/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ messages: [{ role: 'user', content: customText }], currentRequirement: { language: 'english', intent: 'unknown', categorySlug: null, productType: null, room: null, application: null, needs: [], preferredColours: [], preferredPatterns: [], preferredMaterials: [], preferredStyles: [], budgetMinPaise: null, budgetMaxPaise: null, measurements: { widthCm: null, heightCm: null, lengthCm: null, mattressWidthCm: null, mattressLengthCm: null, mattressDepthCm: null }, missingRequiredFields: [], nextQuestion: null } }) }); const data = await response.json(); if (!response.ok) throw new Error(); const intent = data.intent; const installationType = /window/i.test(intent.productType || '') ? 'window' : /door/i.test(intent.productType || '') ? 'door' : null; const length = intent.measurements?.heightCm ? Math.round(intent.measurements.heightCm / 2.54) : null; const actualLengths = availableLengths(filterCurtainCandidates(products, { ...emptyCurtainFinderState(), installationType })); setState({ ...emptyCurtainFinderState(), installationType, requiredLengthInches: length && actualLengths.includes(length) ? length : null, opacityPreference: intent.needs?.some((item: string) => /room dark/i.test(item)) ? 'more-private' : intent.needs?.some((item: string) => /blackout/i.test(item)) ? 'blackout' : intent.needs?.length ? 'bright' : null, colourFamily: intent.preferredColours?.some((item: string) => /grey|beige|white|neutral|cream/i.test(item)) ? 'neutral' : null, pattern: null, budgetMinPaise: intent.budgetMinPaise, budgetMaxPaise: intent.budgetMaxPaise }); setInterpreted(true) } catch { toast.error('I could not understand that. Try the visual finder instead.') } finally { setLoading(false) } }
  const reset = () => { setState(emptyCurtainFinderState()); setStepIndex(0); setMode('hero'); setResults([]); setCustomOpen(false); setInterpreted(false); setCustomText('') }
  const selected = activeStep === 'installation' ? state.installationType : activeStep === 'length' ? state.requiredLengthInches ? String(state.requiredLengthInches) : null : activeStep === 'light' ? state.opacityPreference : activeStep === 'colour' ? state.colourFamily : state.pattern

  if (mode === 'hero') return <section className="guided-hero"><p><Sparkles size={15} /> Alemah Home Advisor</p><h1>Find the right curtain<br />in under <em>30 seconds.</em></h1><span>Answer a few simple questions and we’ll compare the curtains currently available in Alemah’s catalogue.</span><div><button disabled={loading} onClick={() => setMode('wizard')} type="button">{loading ? <><LoaderCircle className="animate-spin" size={16} /> Preparing your curtain finder</> : 'Find My Curtain'}</button><button className="guided-text-button" disabled={loading} onClick={() => setCustomOpen(true)} type="button">I already know what I need</button></div><p aria-live="polite" className="guided-loading-note">{loading ? 'Loading live curtain availability…' : `${products.length} live curtain options ready to compare.`}</p>{customOpen ? <div className="guided-custom"><label htmlFor="custom-request">Tell us in your own words</label><textarea id="custom-request" maxLength={1000} onChange={(event) => setCustomText(event.target.value)} placeholder="I need a 5-foot curtain for a beige bedroom that keeps the room bright." value={customText} />{interpreted ? <><p>Here’s what I understood. You can continue and change any choice.</p><button onClick={() => { setMode('wizard'); setCustomOpen(false); setInterpreted(false) }} type="button">Looks right</button></> : <button disabled={loading || !customText.trim()} onClick={() => void customSubmit()} type="button">Understand my request <Send size={15} /></button>}</div> : null}</section>
  if (mode === 'results') return <section className="guided-results"><header><p><Sparkles size={14} /> Alemah Home Advisor</p><h1>Your best curtain matches</h1><span>Based on {summary.map((item) => item[1]).join(' · ')}</span><div><b>{candidates.length} products compared</b><button onClick={() => { setMode('wizard'); setStepIndex(0) }} type="button">Edit answers</button><button onClick={reset} type="button">Start again</button></div></header>{results.length ? <div className="guided-result-grid">{results.map((product, index) => <article className={index === 0 ? 'is-primary' : ''} key={product.id}><div className="guided-result-image">{product.imageUrl ? <Image alt={product.title} height={600} sizes="(max-width: 768px) 100vw, 33vw" src={product.imageUrl} width={600} /> : null}<b>{index === 0 ? 'Best match' : index === 1 ? 'Alternative style' : 'Value alternative'} · {product.score}%</b></div><div className="guided-result-copy"><h2>{product.title}</h2><p>{[product.attributes.size, product.productType, product.opacity, product.colour, product.pattern, product.material, product.packQuantity ? `Pack of ${product.packQuantity}` : null].filter(Boolean).join(' · ')}</p><strong>{formatPrice(product.sellingPricePaise)}</strong><ul>{product.reasons.map((reason) => <li key={reason}><Check size={14} />{reason}</li>)}</ul>{product.warning ? <aside>{product.warning} Verify panel width before ordering.</aside> : null}<div><Link href={product.variantId ? `${product.productUrl}?variant=${product.variantId}` : product.productUrl}>View product</Link><AddRecommendation product={product} /></div></div></article>)}</div> : <div className="guided-no-match"><h2>No exact match is currently available.</h2><p>Try keeping the installation type while changing the colour, light preference, or length.</p></div>}<div className="guided-refinements"><strong>Want to adjust the result?</strong><button onClick={() => { const nextState = { ...state, colourFamily: 'neutral' as const }; void showResults(nextState) }} type="button">Show neutral colours</button><button onClick={() => { const nextState = { ...state, opacityPreference: 'bright' as const }; void showResults(nextState) }} type="button">Keep the room brighter</button><button onClick={() => { const nextState = { ...state, colourFamily: 'all' as const }; void showResults(nextState) }} type="button">Remove colour preference</button><button onClick={() => { setMode('wizard'); setStepIndex(1) }} type="button">Change size</button></div></section>
  return <section className="guided-shell"><header><p><Sparkles size={14} /> Alemah Home Advisor</p><span>Step {stepIndex + 1} of {steps.length}</span><i><em style={{ width: `${((stepIndex + 1) / steps.length) * 100}%` }} /></i></header><div className="guided-layout"><main><div className="guided-assistant-mark">A</div><p className="guided-kicker">Curtain finder</p><h1>{question[0]}</h1><p className="guided-help">{question[1]}</p><p className="guided-count" aria-live="polite"><strong>{candidates.length}</strong> curtains currently match</p><fieldset><legend className="sr-only">{question[0]}</legend><div className={`guided-options ${activeStep === 'colour' ? 'is-colours' : ''}`}>{options().map((option) => <button aria-pressed={selected === option.value} className={`${selected === option.value ? 'is-selected' : ''} ${option.tone ? `tone-${option.tone}` : ''}`} disabled={!option.count} key={option.value} onClick={() => setAnswer(option.value)} type="button"><span>{selected === option.value ? <Check size={18} /> : null}</span><strong>{option.label}</strong><small>{option.description}</small><b>{option.count} available</b></button>)}</div></fieldset>{activeStep === 'length' ? <><button className="guided-measure-button" onClick={() => setMeasureOpen(!measureOpen)} type="button"><Ruler size={16} /> Help me measure</button>{measureOpen ? <div className="guided-measure"><ol><li>Start at the top of the installed curtain rod.</li><li>Measure down to where you want the fabric to end.</li><li>Enter the value below.</li></ol><div><input inputMode="decimal" onChange={(event) => setMeasurement(event.target.value)} placeholder="Measurement" value={measurement} /><select onChange={(event) => setUnit(event.target.value as typeof unit)} value={unit}><option value="feet">Feet</option><option value="inches">Inches</option><option value="cm">CM</option></select><button onClick={applyMeasurement} type="button">Use measurement</button></div></div> : null}</> : null}</main><aside><h2>Your choices</h2>{summary.length ? summary.map(([label, value], index) => <div key={label}><span>{label}</span><strong>{value}</strong><button onClick={() => setStepIndex(index)} type="button">Change</button></div>) : <p>Your selections will appear here.</p>}<button className="guided-reset" onClick={reset} type="button"><RotateCcw size={15} /> Reset finder</button></aside></div><footer><button onClick={back} type="button"><ChevronLeft size={17} /> Back</button><button disabled={!selected || resultLoading} onClick={next} type="button">{resultLoading ? 'Finding matches…' : stepIndex === steps.length - 1 ? 'See my matches' : 'Continue'}</button></footer></section>
}
